CLIENT_ID = "your_kroger_client_id"
CLIENT_SECRET = "your_kroger_client_secret"
OAUTH2_BASE_URL = "https://api.kroger.com/v1/connect/oauth2"
API_BASE_URL = "https://api.kroger.com/v1"
REDIRECT_URL = "your_redirect_url"
