"""Initial schema with all tables

Revision ID: 00b31406199b
Revises: 
Create Date: 2026-02-16 05:20:34.398385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b31406199b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery_lists_recipe_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_lists_recipe_ingredients',
    sa.Column('grocery_list_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_ingredient_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ),
    sa.ForeignKeyConstraint(['recipe_ingredient_id'], ['recipes_ingredients.id'], )
    )
    # ### end Alembic commands ###
